### ISSUE TITLE
Console won't interrupt on 'Waiting for additional authentication'

### ISSUE THREAD

**Issue by kwcrook** [byu-oit/awslogin#12] opened 2017-07-19 22:26 UTC
I realize this is an edge case and is more cosmetic than anything, but in the situation where the user didn't receive a push and needs to retry logging in, awslogin does not seem to allow for keyboard interrupts, or it takes a while for it to realize that there was a keyboard interrupt before it quits.

#### I'm submitting a …

-   [x] bug report
-   [ ] feature request
-   [ ] support request

#### Requested by:
IDT-kcrook

#### Current behavior
During 'waiting for additional authentication', keyboard interrupts take a while to give control back to the user unless the console is force-quit and restarted.

#### Expected / new behavior
Normal keyboard interrupt (Ctrl+C) behavior, quitting out of waiting for the MFA token

#### Minimal reproduction of the problem with instructions
1. awslogin
2. (Enter username and password)
3. Ctrl+C

**Comment by pauldeden** [comment] 2017-07-20 17:04
I can't reproduce this on Macos

**Comment by pauldeden** [comment] 2017-07-20 17:04
@IDT-kcrook can you show this to me?

**Comment by pauldeden** [comment] 2017-07-20 17:06
@IDT-kcrook I'm available now in the War Room if you have time to show me now.

**Comment by pauldeden** [comment] 2017-07-20 17:13
This bug seems to be windows-only.  It definitely happens on windows 10 and doesn't happen on Macosx.  The problem is bigger than I thought.  It takes about a minute to timeout and register the cntr-c and the whole terminal blocks.

**Comment by ndpete** [comment] 2017-07-20 17:24
Work around while I try to figure this out is to use Ctrl + Break on windows. Sometimes Break is the pause key. This bug is due to the way Windows handles Ctrl+C(SIGINT) vs Ctrl+Break(SIGBREAK) and what not.

**Comment by pauldeden** [comment] 2017-08-10 18:02
Unless there are any other ideas on how to fix this I will close the issue because @ndpete gave a work-a-round.

**Comment by pauldeden** [comment] 2017-08-14 22:17
Closing since there wasn't any other ideas on how to fix this and the work-a-round exists.

**Closed as completed by pauldeden** 2017-08-14 22:17 UTC
Labels: bug
