### ISSUE TITLE
awslogin --account all --role ReadOnly broken?

### ISSUE THREAD

**Issue by kwcrook** [byu-oit/awslogin#44] opened 2018-01-16 21:27 UTC
rv = self.invoke(ctx)                                                                                                                                                                                  
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke                                                                                                                         
    return ctx.invoke(self.callback, **ctx.params)                                                                                                                                                         
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke                                                                                                                         
    return callback(*args, **kwargs)                                                                                                                                                                       
  File "/usr/local/lib/python2.7/site-packages/byu_awslogin/index.py", line 71, in cli                                                                                                                     
    cached_login(account, role, profile, region, adfs_auth_result)                                                                                                                                         
  File "/usr/local/lib/python2.7/site-packages/byu_awslogin/login.py", line 22, in cached_login                                                                                                            
    non_cached_login(account, role, profile, region)                                                                                                                                                       
  File "/usr/local/lib/python2.7/site-packages/byu_awslogin/login.py", line 45, in non_cached_login                                                                                                        
    _perform_login(adfs_auth_result, saml_assertion, account, role, profile, net_id, region)                                                                                                               
  File "/usr/local/lib/python2.7/site-packages/byu_awslogin/login.py", line 53, in _perform_login                                                                                                          
    aws_session_token = assume_role(account_role_to_assume, saml_assertion.assertion)                                                                                                                      
  File "/usr/local/lib/python2.7/site-packages/byu_awslogin/auth/assume_role.py", line 44, in assume_role                                                                                                  
    DurationSeconds=3600,                                                                                                                                                                                  
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 317, in _api_call                                                                                                                 
    return self._make_api_call(operation_name, kwargs)                                                                                                                                                     
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 615, in _make_api_call                                                                                                            
    raise error_class(parsed_response, operation_name)                                                                                                                                                     
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRoleWithSAML operation: User null is not authorized to perform: sts:AssumeRoleWithSAML on resource: arn:aws:iam::1
16585688941:role/ReadOnly

**Comment by bwinterton** [comment] 2018-01-16 21:29
Duplicate of #43

**Comment by ndpete** [comment] 2018-01-17 16:17
This has been resolved.

**Closed as completed by ndpete** 2018-01-17 16:17 UTC
Labels: duplicate
